#!/bin/sh

set -o errexit   # abort an any nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # abort if earlier pipeline command fails

pandoc \
    --output docs/resume.html \
    --standalone \
    --quiet \
    docs/resume.md
echo "wrote docs/resume.html"

pandoc \
    --output docs/resume.pdf \
    -V margin-top=2cm \
    -V margin-bottom=2cm \
    -V margin-left=4cm \
    -V margin-right=4cm \
    docs/resume.md
echo "wrote docs/resume.pdf"
