#!/bin/sh

set -o errexit   # abort an any nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # abort if earlier pipeline command fails

wkhtmltopdf --allow docs docs/resume.html docs/resume.pdf
